2025-01-16 12:47:23,645 INFO    MainThread:26569 [wandb_setup.py:_flush():68] Current SDK version is 0.19.3
2025-01-16 12:47:23,645 INFO    MainThread:26569 [wandb_setup.py:_flush():68] Configure stats pid to 26569
2025-01-16 12:47:23,645 INFO    MainThread:26569 [wandb_setup.py:_flush():68] Loading settings from /home/easy/.config/wandb/settings
2025-01-16 12:47:23,645 INFO    MainThread:26569 [wandb_setup.py:_flush():68] Loading settings from /home/easy/yin/robot_arm/opensource_prj/orin-act-plus/act-plus-plus/wandb/settings
2025-01-16 12:47:23,645 INFO    MainThread:26569 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-16 12:47:23,646 INFO    MainThread:26569 [wandb_init.py:_log_setup():598] Logging user logs to /home/easy/yin/robot_arm/opensource_prj/orin-act-plus/act-plus-plus/wandb/run-20250116_124723-8mwjvd41/logs/debug.log
2025-01-16 12:47:23,646 INFO    MainThread:26569 [wandb_init.py:_log_setup():599] Logging internal logs to /home/easy/yin/robot_arm/opensource_prj/orin-act-plus/act-plus-plus/wandb/run-20250116_124723-8mwjvd41/logs/debug-internal.log
2025-01-16 12:47:23,646 INFO    MainThread:26569 [wandb_init.py:init():714] calling init triggers
2025-01-16 12:47:23,646 INFO    MainThread:26569 [wandb_init.py:init():719] wandb.init called with sweep_config: {}
config: {}
2025-01-16 12:47:23,646 INFO    MainThread:26569 [wandb_init.py:init():745] starting backend
2025-01-16 12:47:23,853 INFO    MainThread:26569 [wandb_init.py:init():749] sending inform_init request
2025-01-16 12:47:23,856 INFO    MainThread:26569 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-16 12:47:23,857 INFO    MainThread:26569 [wandb_init.py:init():764] backend started and connected
2025-01-16 12:47:23,858 INFO    MainThread:26569 [wandb_init.py:init():857] updated telemetry
2025-01-16 12:47:23,865 INFO    MainThread:26569 [wandb_init.py:init():889] communicating run to backend with 90.0 second timeout
2025-01-16 12:47:23,977 ERROR   MainThread:26569 [wandb_init.py:init():918] encountered error: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity moma not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-01-16 12:47:23,977 ERROR   MainThread:26569 [wandb_init.py:init():1378] error in wandb.init()
Traceback (most recent call last):
  File "/home/easy/anaconda3/envs/act-plus/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1368, in init
    return wi.init(run_settings)
  File "/home/easy/anaconda3/envs/act-plus/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 924, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity moma not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-01-16 12:47:23,985 WARNING MsgRouterThr:26569 [router.py:message_loop():75] message_loop has been closed
